-- Ejecuta este script una sola vez en Supabase > SQL Editor

create table if not exists public.investment_capital_movements (
    id bigint generated by default as identity primary key,
    investment_id bigint not null references public.investments(id) on delete cascade,
    movement_date date not null,
    movement_type text not null check (movement_type in ('Aportación','Retiro')),
    amount numeric(18,2) not null check (amount > 0),
    notes text,
    created_at timestamptz not null default now()
);

create index if not exists idx_investment_capital_movements_investment_date
on public.investment_capital_movements (investment_id, movement_date);
