-- Apartados mensuales por categoría y responsable
create table if not exists public.monthly_reserves (
    id bigint generated by default as identity primary key,
    year integer not null,
    category text not null,
    holder text not null,
    monthly_amount numeric(14,2) not null default 0,
    start_month integer not null default 1 check (start_month between 1 and 12),
    current_balance numeric(14,2) not null default 0,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index if not exists monthly_reserves_year_category_holder_uidx
on public.monthly_reserves (year, category, holder);

alter table public.monthly_reserves enable row level security;

drop policy if exists "monthly_reserves_select" on public.monthly_reserves;
drop policy if exists "monthly_reserves_insert" on public.monthly_reserves;
drop policy if exists "monthly_reserves_update" on public.monthly_reserves;
drop policy if exists "monthly_reserves_delete" on public.monthly_reserves;

create policy "monthly_reserves_select"
on public.monthly_reserves for select
using (true);

create policy "monthly_reserves_insert"
on public.monthly_reserves for insert
with check (true);

create policy "monthly_reserves_update"
on public.monthly_reserves for update
using (true)
with check (true);

create policy "monthly_reserves_delete"
on public.monthly_reserves for delete
using (true);
