create table if not exists movements (
  id bigint generated by default as identity primary key,
  fingerprint text unique not null,
  description text, movement_date date not null, amount numeric not null,
  category text, subcategory text, family_member text, tag text, account text,
  source_file text, imported_at timestamptz default now()
);
create index if not exists movements_date_idx on movements(movement_date);
create index if not exists movements_category_idx on movements(category);

create table if not exists investments (
  id bigint generated by default as identity primary key,
  institution text not null, product text, owner text, asset_type text,
  currency text default 'MXN', balance numeric not null default 0,
  annual_rate numeric default 0, opened_on date, maturity_date date,
  liquidity text, notes text, updated_at timestamptz default now()
);

create table if not exists investment_operations (
  id bigint generated by default as identity primary key,
  investment_id bigint references investments(id) on delete cascade,
  operation_date date not null, operation_type text not null,
  amount numeric not null, tax numeric default 0, notes text,
  created_at timestamptz default now()
);

create table if not exists imports (
  id bigint generated by default as identity primary key,
  file_name text not null, row_count integer not null, new_rows integer not null,
  duplicate_rows integer not null, imported_at timestamptz default now()
);

alter table movements enable row level security;
alter table investments enable row level security;
alter table investment_operations enable row level security;
alter table imports enable row level security;

-- No se crean políticas públicas. La aplicación usa la clave service_role
-- exclusivamente como secreto del servidor de Streamlit; nunca va al navegador.
